reminder_emails:   # * * * * * : Min Hour Day month week
  cron: "* 0 * * *"  # 00:00 am
  class: "ReminderEmailJob"
  queue: default

review_reminder:
  cron: "0 0 * * *"  # Runs at midnight every day
  class: "ReviewReminderCronJob"
  queue: default